version: '2'
services:
  ec2:
    build:
      context: .
      args:
          USER: ec2-user
    container_name: ec2
    stdin_open: true
    tty: true
    ports:
      - "2022:22"
    volumes:
      - .:/share
